/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRouteImport } from './routes/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KsiegaGosciRouteImport } from './routes/ksiega-gosci'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as TajneArchiwumJana99RouteImport } from './routes/tajne-archiwum-jana-99'
import { Route as WeryfikacjaRouteImport } from './routes/weryfikacja'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRoute =
  WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRouteImport.update({
    id: '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF',
    path: '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF',
    getParentRoute: () => rootRouteImport,
  } as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KsiegaGosciRoute = KsiegaGosciRouteImport.update({
  id: '/ksiega-gosci',
  path: '/ksiega-gosci',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const TajneArchiwumJana99Route = TajneArchiwumJana99RouteImport.update({
  id: '/tajne-archiwum-jana-99',
  path: '/tajne-archiwum-jana-99',
  getParentRoute: () => rootRouteImport,
} as any)
const WeryfikacjaRoute = WeryfikacjaRouteImport.update({
  id: '/weryfikacja',
  path: '/weryfikacja',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF': typeof WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/ksiega-gosci': typeof KsiegaGosciRoute
  '/menu': typeof MenuRoute
  '/tajne-archiwum-jana-99': typeof TajneArchiwumJana99Route
  '/weryfikacja': typeof WeryfikacjaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF': typeof WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/ksiega-gosci': typeof KsiegaGosciRoute
  '/menu': typeof MenuRoute
  '/tajne-archiwum-jana-99': typeof TajneArchiwumJana99Route
  '/weryfikacja': typeof WeryfikacjaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF': typeof WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/ksiega-gosci': typeof KsiegaGosciRoute
  '/menu': typeof MenuRoute
  '/tajne-archiwum-jana-99': typeof TajneArchiwumJana99Route
  '/weryfikacja': typeof WeryfikacjaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF'
    | '/galeria'
    | '/kontakt'
    | '/ksiega-gosci'
    | '/menu'
    | '/tajne-archiwum-jana-99'
    | '/weryfikacja'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF'
    | '/galeria'
    | '/kontakt'
    | '/ksiega-gosci'
    | '/menu'
    | '/tajne-archiwum-jana-99'
    | '/weryfikacja'
  id:
    | '__root__'
    | '/'
    | '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF'
    | '/galeria'
    | '/kontakt'
    | '/ksiega-gosci'
    | '/menu'
    | '/tajne-archiwum-jana-99'
    | '/weryfikacja'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRoute: typeof WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRoute
  GaleriaRoute: typeof GaleriaRoute
  KontaktRoute: typeof KontaktRoute
  KsiegaGosciRoute: typeof KsiegaGosciRoute
  MenuRoute: typeof MenuRoute
  TajneArchiwumJana99Route: typeof TajneArchiwumJana99Route
  WeryfikacjaRoute: typeof WeryfikacjaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF': {
      id: '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF'
      path: '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF'
      fullPath: '/WDDGUHSDFSODIFUFSDJHFSOUDFHSDF'
      preLoaderRoute: typeof WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksiega-gosci': {
      id: '/ksiega-gosci'
      path: '/ksiega-gosci'
      fullPath: '/ksiega-gosci'
      preLoaderRoute: typeof KsiegaGosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tajne-archiwum-jana-99': {
      id: '/tajne-archiwum-jana-99'
      path: '/tajne-archiwum-jana-99'
      fullPath: '/tajne-archiwum-jana-99'
      preLoaderRoute: typeof TajneArchiwumJana99RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weryfikacja': {
      id: '/weryfikacja'
      path: '/weryfikacja'
      fullPath: '/weryfikacja'
      preLoaderRoute: typeof WeryfikacjaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRoute: WDDGUHSDFSODIFUFSDJHFSOUDFHSDFRoute,
  GaleriaRoute: GaleriaRoute,
  KontaktRoute: KontaktRoute,
  KsiegaGosciRoute: KsiegaGosciRoute,
  MenuRoute: MenuRoute,
  TajneArchiwumJana99Route: TajneArchiwumJana99Route,
  WeryfikacjaRoute: WeryfikacjaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
